name: sociality
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  bot_toast: ^4.0.2
  fluttertoast: ^8.0.9
  flutter_svg: ^2.0.7
  flutter_zoom_drawer: ^3.0.3
  flutter_iconly: ^1.0.2
  flutter_switch: ^0.3.2
  fluttericon: ^2.0.0
  rflutter_alert: ^2.0.4
  image_picker: ^1.0.1
  photo_view: ^0.14.0
  conditional_builder_null_safety: ^0.0.6
  full_screen_image_null_safe: any
  bubble: ^1.2.1
  scrollable_positioned_list: ^0.3.2
  badges: ^3.1.1
  carousel_slider: ^4.1.1
  timeago: ^3.3.0
  dio: ^5.2.1+1
  flutter_screenutil: ^5.7.0
  cached_network_image: ^3.2.3
  wakelock: ^0.6.2
  google_fonts: any
  gallery_saver: any
  dart_code_metrics: ^5.7.6

  # firebase
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0
  google_sign_in: ^6.1.4
  firebase_storage: ^11.0.6
  firebase_messaging: ^14.1.3
  intl: ^0.18.1
  shimmer: ^3.0.0
  story: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
  


flutter_assets:
  assets_path: assets/images/
  output_path: lib/
  filename: image_assets.dart
  field_prefix: