name: socialite
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  bot_toast: ^4.0.2
  fluttertoast: ^8.0.9
  flutter_iconly: ^1.0.2
  image_picker: ^1.0.1
  conditional_builder_null_safety: ^0.0.6
  bubble: ^1.2.1
  badges: ^3.1.2
  carousel_slider: ^4.1.1
  timeago: ^3.3.0
  dio: ^5.2.1+1
  flutter_screenutil: ^5.7.0
  cached_network_image: ^3.2.3
  google_fonts: ^6.1.0
  fluttericon: ^2.0.0
  full_screen_image_null_safe: any

  # firebase
  firebase_core: ^2.3.0 
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0
  google_sign_in: ^6.1.4
  firebase_storage: ^11.0.6
  firebase_messaging: ^14.1.3
  intl: ^0.18.1
  shimmer: ^3.0.0
  image_cropper: ^5.0.0
  awesome_dialog: ^3.1.0
  url_launcher: ^6.1.6
  scrollable_positioned_list: ^0.3.8
  flutter_svg: ^2.0.7
  uuid: ^4.1.0
  connectivity_plus: ^5.0.1
  glassmorphism: ^3.0.0
  emoji_picker_flutter: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3



flutter:
  uses-material-design: true

  assets:
    - assets/images/
  


flutter_assets:
  assets_path: assets/images/
  output_path: lib/
  filename: image_assets.dart
  field_prefix: